/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#030d14",
        "surface-dim": "#010609",
        "surface-bright": "#0a1f2e",
        "surface-container-lowest": "#010406",
        "surface-container-low": "#06131c",
        "surface-container": "#081a26",
        "surface-container-high": "#0d2536",
        "surface-container-highest": "#133147",
        "surface-variant": "#133147",
        "on-surface": "#e0e6ed",
        "on-surface-variant": "#94a3b8",
        "inverse-surface": "#e0e6ed",
        "inverse-on-surface": "#030d14",
        "outline": "#475569",
        "outline-variant": "#334155",
        "surface-tint": "#e33e39",
        "primary": "#e33e39",
        "primary-container": "#851c18",
        "on-primary": "#ffffff",
        "on-primary-container": "#fad6d5",
        "primary-fixed": "#ff7975",
        "primary-fixed-dim": "#e33e39",
        "on-primary-fixed": "#4a0b08",
        "on-primary-fixed-variant": "#6b1410",
        "inverse-primary": "#b02a26",
        "secondary": "#00e5ff",
        "secondary-container": "#005e6b",
        "on-secondary": "#001a1d",
        "on-secondary-container": "#ccfaff",
        "secondary-fixed": "#66efff",
        "secondary-fixed-dim": "#00e5ff",
        "on-secondary-fixed": "#002a2f",
        "on-secondary-fixed-variant": "#004047",
        "tertiary": "#ffffff",
        "tertiary-container": "#d1d5db",
        "on-tertiary": "#000000",
        "on-tertiary-container": "#374151",
        "tertiary-fixed": "#f3f4f6",
        "tertiary-fixed-dim": "#e5e7eb",
        "on-tertiary-fixed": "#111827",
        "on-tertiary-fixed-variant": "#1f2937",
        "error": "#ef4444",
        "error-container": "#991b1b",
        "on-error": "#ffffff",
        "on-error-container": "#fecaca",
        "background": "#030d14",
        "on-background": "#e0e6ed",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "2xl": "0.75rem",
        "full": "9999px",
      },
      spacing: {
        "gutter-lg": "1.5rem",
        "margin-lg": "2rem",
        "space-md": "0.75rem",
        "margin": "1rem",
        "space-lg": "1rem",
        "margin-md": "1.5rem",
        "space-xl": "1.5rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "gutter": "1rem",
      },
      fontFamily: {
        sans: ["Geist", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        "headline-xl": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "body-lg": ["Geist", "sans-serif"],
        "body-md": ["Geist", "sans-serif"],
        "body-sm": ["Geist", "sans-serif"],
        "mono-metric": ["JetBrains Mono", "monospace"],
        "mono-code": ["JetBrains Mono", "monospace"],
        "label-caps": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "label-caps": ["11px", { lineHeight: "14px", letterSpacing: "0.06em", fontWeight: "500" }],
        "headline-xl": ["36px", { lineHeight: "44px", letterSpacing: "-0.025em", fontWeight: "600" }],
        "mono-code": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-xl-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "mono-metric": ["20px", { lineHeight: "24px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "500" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
